x-cmd: &cmd
  command:  [ "python", "hello_world_my.py" ]

services:
  app:
    image: docker-compose-test:1.0
    environment:
      - DOCKER_ENV=Compose test docker (app)
      - DOCKER_ENV_INT_ARG=1
    build: Dockerfiles-dir/app

# Using envs from file
  app2:
    image: docker-compose-test:1.2
    env_file: Dockerfiles-dir/app2/env
    build: Dockerfiles-dir/app2


# Using not own Dockerfile with modified CMD
  app3:
    image: docker-compose-test:1.3
    environment:
      - DOCKER_ENV=Compose test docker (app3)
      - DOCKER_ENV_INT_ARG=3
    <<: *cmd

  app4:
    image: docker-compose-test:1.4
    environment:
      - DOCKER_ENV=Compose test docker (app4)
      - DOCKER_ENV_INT_ARG=4
    build: Dockerfiles-dir/app4

  app5:
    image: docker-compose-test:1.5
    environment:
      - DOCKER_ENV=Compose test docker (app5)
      - DOCKER_ENV_INT_ARG=5
    build: Dockerfiles-dir/app5
